### ISSUE TITLE
Plugin does not exist: \SergiuParaschiv\PHPCI\Plugin\Eslint

### ISSUE THREAD

**Issue by ImmortalJoker** [sergiu-paraschiv/PHPCI-eslint#2]
Hey there,

after installing your module PHPCI shows me error message which is on the title.

Any thoughts?!

**Comment by sergiu-paraschiv** [comment]
Hi,

Maybe composer build cache?
What's your setup?

**Comment by olmer** [comment]
Hi Sergiu. Thank you for a quick reply. We are adding you package to "require-dev", updating it afterwards and trying to build project in PHPCI. Eslint config is added to phpci.yml file into "setup" node.

```yml
build_settings:
  clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone entire repo
  ignore:
    - "vendor"
    - "tests"
    - "bootstrap/cache"
    - "bootstrap/autoload.php"
    - "modules/*/Database/Migrations"
setup:
  composer:
    action: "install"
  \SergiuParaschiv\PHPCI\Plugin\Eslint:
    directory: "resources/assets/frontend/js/"
    command: "npm run lint:ci"
    allowed_errors: 0
    allowed_warnings: 0
    data_offset: 2

test:
  php_mess_detector:
    allow_failures: false
    rules:
      - "phpci/phpmd.xml"
```
